name: corsac_router
version: 0.2.0-nullsafety
description: Simple HTTP routing library for server-side applications.
homepage: https://github.com/ImperialOctopus/router

environment:
  sdk: ">=2.10.0-4.0.dev <3.0.0"

dependencies:
  collection: ^1.15.0-nullsafety.2

dev_dependencies:
  test: ^1.16.0-nullsafety.2
  pedantic: ^1.10.0-nullsafety
