name: corsac_router
version: 0.2.0-nullsafety.1
description: Simple HTTP routing library for server-side applications.
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/corsac-dart/router

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  quiver: ^2.1.3

dev_dependencies:
  test: ^1.16.0-nullsafety.2
